const UPDATE_USERAPI_DETAILS = 'UPDATE_USERAPI_DETAILS';
const UPDATE_USERTORRE_DETAILS = 'UPDATE_USERTORRE_DETAILS';
const USER_RECORD = 'USER_RECORD';

export {
  UPDATE_USERAPI_DETAILS,
  UPDATE_USERTORRE_DETAILS,
  USER_RECORD,
};
